name: CI

# ワークフローが実行されるトリガー
on:
  # developブランチにプッシュされたとき
  push:
    branches: ["develop"]
  # developブランチに対するプルリクエストが作成されたとき
  pull_request:
    branches: ["develop"]

# 実行するジョブを定義
jobs:
  # Lintとフォーマットチェックのジョブ
  lint:
    name: Lint and Format Check
    # ジョブを実行する仮想マシンのOSを指定
    runs-on: ubuntu-latest

    # ジョブのステップを定義
    steps:
      # 1. リポジトリのソースコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Bunの実行環境をセットアップ
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.17"
          cache: true

      # 依存関係のインストール
      - name: Install dependencies
        run: bun install

      # Lintの実行
      - name: Run Lint
        run: bun run lint

      # フォーマットの実行
      - name: Run Format Check
        run: bun run format:check

  # テストのジョブ
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.17"
          cache: true

      - name: Install dependencies
        run: bun install

      - name: Run Tests
        run: bun test

  # ビルドのジョブ
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.17"
          cache: true

      - name: Install dependencies
        run: bun install

      - name: Build Project
        run: bun run build
